### ISSUE TITLE
client-server example error expected vs gotten is reversed

### ISSUE THREAD

**Issue by jdamme** [rpclib/rpclib#130]
I wanted to test a simple client-server example.

To make it compile i had to link with Thread lib. Currently it is not in CMakeLists.txt.
I dunno if it is linked somewhere else when calling cmake to make the examples.

Anyhow: 
CMakeLists.txt
```
cmake_minimum_required(VERSION 3.0.0)
project(rpclib-test)

find_package(Threads REQUIRED)
find_package(rpclib REQUIRED)

include_directories(${RPCLIB_INCLUDE_DIR})

add_executable(server server.cpp)
set_property(TARGET server PROPERTY CXX_STANDARD 11)
target_link_libraries(server ${RPCLIB_LIBS})
target_link_libraries(server ${CMAKE_THREAD_LIBS_INIT})

add_executable(client client.cpp)
set_property(TARGET client PROPERTY CXX_STANDARD 11)
target_link_libraries(client ${RPCLIB_LIBS})
target_link_libraries(client ${CMAKE_THREAD_LIBS_INIT})
```

client.cpp
```
#include <iostream>
#include "rpc/client.h"
#include "rpc/rpc_error.h"

int main() {
    rpc::client client("127.0.0.1", rpc::constants::DEFAULT_PORT);
    
    try
    {
      std::cout << "Calling add 2 3" << std::endl;
      auto result = client.call("add", 2, 3).as<int>();
      std::cout << "The result is: " << result << std::endl;
    }
    catch (rpc::rpc_error &e) {
      std::cout << "in function " << e.get_function_name() << ": ";
      std::cout << e.what() << std::endl;
      std::cout << e.get_error().as<std::string>() << std::endl;
    }
    
    try
    {
      std::cout << "Calling foo" << std::endl;
      client.call("foo");
    }
    catch (rpc::rpc_error &e) {
      std::cout << "in function " << e.get_function_name() << ": ";
      std::cout << e.what() << std::endl;
      std::cout << e.get_error().as<std::string>() << std::endl;
    }
    
    try
    {
      std::cout << "Calling foo 10" << std::endl;
      client.call("foo", 10);
    }
    catch (rpc::rpc_error &e) {
      std::cout << "in function " << e.get_function_name() << ": ";
      std::cout << e.what() << std::endl;
      std::cout << e.get_error().as<std::string>() << std::endl;
    }
    
    try
    {
      std::cout << "Calling bad 3" << std::endl;
      client.call("bad", 3);
    }
    catch (rpc::rpc_error &e) {
      std::cout << "in function " << e.get_function_name() << ": ";
      std::cout << e.what() << std::endl;
      std::cout << e.get_error().as<std::string>() << std::endl;
    }
    
    try
    {
      std::cout << "Calling bad 5" << std::endl;
      client.call("bad", 5);
    }
    catch (rpc::rpc_error &e) {
      std::cout << "in function " << e.get_function_name() << ": ";
      std::cout << e.what() << std::endl;
      std::cout << e.get_error().as<std::string>() << std::endl;
    }

    try
    {
      std::cout << "Calling jibber" << std::endl;
      client.call("jibber");
    }
    catch (rpc::rpc_error &e) {
      std::cout << "in function " << e.get_function_name() << ": ";
      std::cout << e.what() << std::endl;
      std::cout << e.get_error().as<std::string>() << std::endl;
    }
    
    try
    {
      std::cout << "Calling add 2 3 4" << std::endl;
      client.call("add", 2, 3, 4);
    }
    catch (rpc::rpc_error &e) {
      std::cout << "in function " << e.get_function_name() << ": ";
      std::cout << e.what() << std::endl;
      std::cout << e.get_error().as<std::string>() << std::endl;
    }
    
    try
    {
      std::cout << "Calling add 2" << std::endl;
      client.call("add", 2);
    }
    catch (rpc::rpc_error &e) {
      std::cout << "in function " << e.get_function_name() << ": ";
      std::cout << e.what() << std::endl;
      std::cout << e.get_error().as<std::string>() << std::endl;
    }
    
    try
    {
      std::cout << "Calling add" << std::endl;
      client.call("add");
    }
    catch (rpc::rpc_error &e) {
      std::cout << "in function " << e.get_function_name() << ": ";
      std::cout << e.what() << std::endl;
      std::cout << e.get_error().as<std::string>() << std::endl;
    }
    
    return 0;
}
```

server.cpp
```
#include <iostream>
#include "rpc/server.h"

void foo() { std::cout << "foo was called!" << std::endl; }

void bad(int x) {
    if (x == 5) {
        throw std::runtime_error("x == 5. I really don't like 5.");
    }
}

int main() {
    // Create a server that listens on port 8080, or whatever the user selected
    rpc::server srv("0.0.0.0", rpc::constants::DEFAULT_PORT);

    // Binding the name "foo" to free function foo.
    // note: the signature is automatically captured
    srv.bind("foo", &foo);

    // Binding a lambda function to the name "add".
    srv.bind("add", [](int a, int b) { return a + b; });

    // Throwing an exception will cause the server to write
    // an error response. This call will make it also
    // suppress the exception (note that this is not default
    // because this behavior might hide errors in the
    // code).
    srv.suppress_exceptions(true);
    srv.bind("bad", &bad);

    // Run the server loop.
    srv.run();

    return 0;
}
```

Produces this output
```
Calling add 2 3
The result is: 5
Calling foo
Calling foo 10
in function foo: rpc::rpc_error during call
rpclib: client error C0002: Function 'foo' was called with an invalid number of arguments. Expected: 1, got: 0
Calling bad 3
Calling bad 5
in function bad: rpc::rpc_error during call
rpclib: function 'bad' (called with 1 arg(s)) threw an exception. The exception contained this information: x == 5. I really don't like 5..
Calling jibber
in function jibber: rpc::rpc_error during call
rpclib: server could not find function 'jibber' with argument count 0.
Calling add 2 3 4
in function add: rpc::rpc_error during call
rpclib: client error C0002: Function 'add' was called with an invalid number of arguments. Expected: 3, got: 2
Calling add 2
in function add: rpc::rpc_error during call
rpclib: client error C0002: Function 'add' was called with an invalid number of arguments. Expected: 1, got: 2
Calling add
in function add: rpc::rpc_error during call
rpclib: client error C0002: Function 'add' was called with an invalid number of arguments. Expected: 0, got: 2
```
Expected and gotten values a reversed.

Build with : Ubuntu 16.04 g++-5.4

**Comment by sztomi** [comment]
Thanks for taking a look. I meant to remove those examples because the "basic" example is the calculator. But I might keep them with your fix, after all. I'm currently a bit busy with extra work, but for the next release I'll take a look at  your PR (much appreciated!).
